spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf8
    username: root
    password: root

lianjia:
  city:
    districts: liuhe/
    second:
      hand:
        districts:
    sh:
      deal:
        districts: pudong/
pusher:
  communities: 盘金