spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf8
    username: root
    password: root

lianjia:
  city:
    districts: liuhe/

pusher:
  communities: 盘金