spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf8
    username: root
    password: ${HOUSE_DB_PWD}

lianjia:
  city:
    districts: liuhe/
    second:
      hand:
        districts: pudong/,minhang/
    sh:
      deal:
        districts:
pusher:
  communities: 盘金