spring:
  datasource:
    name: online
    url: jdbc:mysql://47.96.107.70:3306/house?characterEncoding=utf8
    username: root
    password: root

lianjia:
  city:
    districts: jianye/,qinhuai/,xuanwu/,yuhuatai/,qixia/,jiangning/,pukou/,liuhe/,lishui/,gaochun/

pusher:
  communities: 蓝筹,阅城