spring:
  datasource:
    name: online
    url: jdbc:mysql://47.96.107.70:3306/house?characterEncoding=utf8
    username: root
    password: ${HOUSE_DB_PWD}

lianjia:
  city:
    districts: jianye/,qinhuai/,xuanwu/,yuhuatai/,qixia/,jiangning/,pukou/,liuhe/,lishui/,gaochun/
    second:
      hand:
        districts: pudong/,minhang/,baoshan/,xuhui/,putuo/,yangpu/,changning/,songjiang/,jiading/,huangpu/,jingan/,hongkou/,qingpu/,fengxian/,jinshan/,chongming/,shanghaizhoubian/
    sh:
      deal:
        districts: pudong/,minhang/,baoshan/,xuhui/,putuo/,yangpu/,changning/,songjiang/,jiading/,huangpu/,jingan/,hongkou/,qingpu/,fengxian/,jinshan/,chongming/,shanghaizhoubian/
pusher:
  communities: 蓝筹,阅城